### PR TITLE
Fit is intenger

### PR DESCRIPTION
**Pull request by PatrickNiyogitare28**
#### What does this PR do?

- Adds integer validator

#### Description of Task to be completed? 

- Integer can be validated

#### How should this be manually tested?

- Clone the repo

- checkout to branche ``fit-isInterger``

- Run `npm install` to install modules

- Run `npm  run test` to run the tests

#### Any background context you want to provide?
- N/A

#### What are the relevant Pivotal Tracker/trello stories?
- N/A

#### Screenshots (if appropriate)
- N/A

#### Questions:
- N/A

### CODE REVIEW

**Review by makuzaverite — CHANGES_REQUESTED** [review]
I think we need a  unit test where test cases might fail.

We also need to add a unit test for a really long number like 2<sup>63</sup>-1

**Comment by makuzaverite** [comment]
@PatrickNiyogitare28  are you still up to this ??

**Comment by PatrickNiyogitare28** [comment]
I'm trying to get time to have this done.

**Review by makuzaverite — APPROVED** [review]
Looks fine for now, thanks!

**Pull request merged**
