### PR TITLE
isDistinct Validator added .

### LINKED ISSUE #101: isDistinct: check if provided array does not have duplicate

### PR DESCRIPTION
**Pull request by pacifiquem**
This PR mplements the following **feature (isDistinct)**

* [ ] Bug
* [x] Feature
* [ ] Breaking changes

**Closing issues**

Fixes #101

### CODE REVIEW

**Review by veritem — CHANGES_REQUESTED** [review]
Yoo thanks, this looks really nice. Would you mind adding this new func to docs on README after that this will get merged and published on npm

**Comment by pacifiquem** [comment]
> Yoo thanks, this looks really nice. Would you mind adding this new func to docs on README after that this will get merged and published on npm

Task finished .

**Review by veritem — APPROVED** [review]
Thanks

**Comment by veritem** [comment]
CI failed https://github.com/veritem/valdie/actions/runs/3886614305/jobs/6632439445 would you mind looking into why that test failed?

**Comment by pacifiquem** [comment]
> CI failed https://github.com/veritem/valdie/actions/runs/3886614305/jobs/6632439445 would you mind looking into why that test failed?

fixed all problems .

**Review by veritem — APPROVED** [review]
Thanks

**Pull request merged**
